### PR TITLE
Bug: Redirect to dashboard if logged in

### PR DESCRIPTION
**Pull request by Arthur236**
## What does this PR do?

Redirects a user to the dashboard if they are logged in.

## Description of Task to be completed?

When a logged in user tries to access the root url, they are redirected back to the dashboard.

## How should this be manually tested?

* Visit the root url and log in
* Load the root url again

## What are the relevant pivotal tracker stories?

[158242466](https://www.pivotaltracker.com/story/show/158242466)

## Any background context you want to add?

N/A

## Important notes

N/A

## Packages installed

N/A

## Deployment note

N/A

## Related PRs branch | PR (branch_name) | (pr_link)

N/A

## Todos
- [x] Raise PR
- [ ] Test
- [ ] Documentation
## Screenshots

N/A

### CODE REVIEW

**Comment by Arthur236** [comment]
Yes. I've tested it several times. The only issue that's there has to do with how the toast messages have been implemented. So the user is not redirected automatically after they log in. They have to reload the page to be redirected

**Comment by sachungo** [comment]
I wonder if we even need the toast message on login - the user will already know they are login upon redirect to dashboard. The toast message will be useful in case of errors but not for successful login

**Comment by sachungo** [comment]
I have raised the question to Eric on Slack...don't merge until he responds

**Comment by Arthur236** [comment]
Is it okay to merge this now?

**Comment by sachungo** [comment]
Yes, go ahead and merge. The issue with success toast message will be looked into later

**Comment by Arthur236** [comment]
Great

**Pull request merged**
