### PR TITLE
#157477450 Setup pull request template

### PR DESCRIPTION
**Pull request by chadwalt**
#### What does this PR do?
Sets up a pull request template
#### Description of Task to be completed?
Currently, there isn't a pull request template. This PR sets up a pull request template.
#### How should this be manually tested?
N/A
#### What are the relevant pivotal tracker stories?
[#157477450](https://www.pivotaltracker.com/story/show/157477450)
#### Any background context you want to add?
N/A
#### Screenshots
N/A

### CODE REVIEW

**Comment by HawiCaesar** [comment]
LGTM

**Comment by chadwalt** [comment]
@theterminalguy I have added those sections.

**Comment by theterminalguy** [comment]
Thanks @chadwalt , a few more requests. 

Can you please add two pounds instead of one to have a level two heading like this `##` example shown below would translate to:

## Important note

And for the todos, add those sections as well. 
## Todos 
- [x] Raise PR 
- [ ] Test
- [ ] Documentation 

which in raw forms look like this

```
## Todos 
- [x] Raise PR 
- [ ] Test
- [ ] Documentation 
```

For the realted PRs it should look like this 

## Related PRs
List related PRs against other branches:

branch | PR
------ | ------
other_pr_production | [link]()
other_pr_master | [link]()

which in raw form is 

## Related PRs
List related PRs against other branches:
```
branch | PR
------ | ------
other_pr_production | [link]()
other_pr_master | [link]()
```
Thanks.

**Comment by chadwalt** [comment]
@theterminalguy I have added the changes requested.

**Comment by theterminalguy** [comment]
Thanks @chadwalt 👍

**Pull request merged**
