### PR TITLE
#157340072 Landing Page  Design Mockup

### PR DESCRIPTION
**Pull request by Awinja-Andela**
#### What does this PR do?
This PR introduces Landing page Design Mockups
#### Description of Task to be completed?
The landing page should only have the button to login via Google, with an appropriate background. 
#### How should this be manually tested?
N/A
#### What are the relevant pivotal tracker stories?
#157340072
#### Screenshots
Blue overlay with blue button
blueoverlay

Dark variation
art landing dark 1

Mobile view for dark variation
art mobile dark

Blue variation
art landing blue

Mobile view for blue variation
art mobile blue

### CODE REVIEW

**Comment by theterminalguy** [comment]
@aimeedyki and @Awinja-Andela can you please provide a mockup for a smaller screen resolution. This looks good. Would love to have another variant.

**Comment by theterminalguy** [comment]
Also, where did you find the pictures from?

**Comment by aimeedyki** [comment]
@theterminalguy we got the picture from google and we went with it as it's the same picture that is used on the mobile app.

**Comment by aimeedyki** [comment]
@theterminalguy We have added another variation and the mobile view. Please review

**Comment by theterminalguy** [comment]
@penny-wanjiru would love your feedback on the mockups above ☝️

**Comment by penny-wanjiru** [comment]
Looks good @Awinja-Andela, just one suggestion could you use a blue overlay (and lower opacity as you have done) on the dark variation and use a blue sign in with google button. Let's see how that will look.

**Comment by penny-wanjiru** [comment]
Question: Are we choosing between the two variations? @Awinja-Andela

**Comment by aimeedyki** [comment]
@penny-wanjiru Yes you are to choose between the two and we have added the variation for the blue overlay and button. Please review. Thanks.
Cc: @Awinja-Andela @theterminalguy

**Pull request closed without merging**
