### PR TITLE
#165785610 update andela centers functionality

### PR DESCRIPTION
**Pull request by Mirriam-Maina**
## What does this PR do?
-  Updates Andela centers functionality
## Description of Task to be completed?
- Removes add Andela Center Button
## How should this be manually tested?
- Run the app
- Click on Andela Centres
- A list of Andela Centres is displayed without an `Add Centre` button

## What are the relevant pivotal tracker stories?
[#165785610](https://www.pivotaltracker.com/story/show/165785610)

## Any background context you want to add?
`N/A`
## Important notes
`N/A`
## Packages installed
`N/A`

## Related PRs branch | PR (branch_name) | (pr_link)
Branch | PR
------ | ------
other_pr_production | [link]()
other_pr_master | [link]()
## Todos
- [x] Raise PR
- [x] Test
- [x] Documentation
## Screenshots

Screenshot 2019-05-09 at 12 37 01

### CODE REVIEW

**Review by fojuri — COMMENTED** [review]
You will also need to remove the actions involved in Adding a center

**Comment by Mirriam-Maina** [comment]
> You will also need to remove the actions involved in Adding a center

@andela-fojuri this has been done

**Comment by fojuri** [comment]
Please update the tests as well.

**Review by fojuri — APPROVED** [review]
Looks good.

**Pull request merged**
